import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Card, Col, Input, Layout, Row, Space, message } from "antd";
import { Fragment, useEffect, useState } from "react";
import Link from "next/link";
const { Header, Content } = Layout;
const { Meta } = Card;
const CLIENT_ID = "81c2bea90bc3404784c215dec09fd94e";
const CLIENT_SECRET = "eab8ce6631f6478e9580a26f761a383e";
export default function Home() {
  const [searchInput, setSearchInput] = useState("");
  const [accessToken, setAccessToken] = useState("");
  const [albums, setAlbums] = useState([]);
  useEffect(() => {
    //API Access Token
    var authParameters = {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: `grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}`,
    };
    fetch("https://accounts.spotify.com/api/token", authParameters)
      .then((response) => response.json())
      .then((data) => setAccessToken(data.access_token));
  }, []);
  // Search
  const search = async () => {
    if (searchInput === "") {
      message.error("Please enter artist name");
      return;
    }
    // Get request using search to get artist ID

    // Get reuest with artist ID grab all the albums from that artist

    // Display those albums to the user
    var artistParameters = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
    };
    var artistID = await fetch(
      `https://api.spotify.com/v1/search?q=${searchInput}&type=artist&market=IN`,
      artistParameters
    )
      .then((response) => response.json())
      .then((data) => {
        console.log(data.artists.items[0].id);
        return data.artists.items[0].id;
      })
      .catch((error) => {
        console.log(error);
      });
    console.log("artistID", artistID);

    var returnedAlbums = await fetch(
      "https://api.spotify.com/v1/artists/" +
        artistID +
        "/albums" +
        "?include_groups=album&market=IN",
      artistParameters
    )
      .then((response) => response.json())
      .then((data) => {
        setAlbums(data.items);
      });
  };
  console.log(albums);
  return (
    <div>
      <Head>
        <title>Spotify Searcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Fragment>
        <Layout style={{ minHeight: "100vh" }}>
          <Header className={styles.header}></Header>
          <Content className={styles.content}>
            <Row
              gutter={[16, 8]}
              align={"middle"}
              width={"100%"}
              // style={{ height: "70%" }}
            >
              <Col style={{ padding: "20px 40px" }} span={24}>
                <Input
                  placeholder="artist name"
                  onChange={(e) => setSearchInput(e.target.value)}
                  onPressEnter={search}
                />
              </Col>
            </Row>
            <Row gutter={[16, 8]} align={"middle"}>
              {albums.map((album, i) => {
                return (
                  <Col span={8} key={i}>
                    <Link href={album.external_urls.spotify}>
                    <Card
                      hoverable
                      cover={<img alt="example" src={album.images[0].url} />}
                    >
                      
                      <Meta
                        title={album.name}
                        // description={album.name}
                      />
                    </Card>
                    </Link>
                  </Col>
                );
              })}
            </Row>
          </Content>
          {/* <Footer className={styles.footer}>Footer</Footer> */}
        </Layout>
      </Fragment>
    </div>
  );
}
